all: display_surface.pdf pcm_channel.pdf riscv.pdf

display_surface.pdf: display_surface.tex 
	pdflatex display_surface.tex 

pcm_channel.pdf: pcm_channel.tex
	pdflatex pcm_channel.tex 

riscv.pdf: riscv.tex riscv_pipeline.tex
	pdflatex riscv.tex
